apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ukeafww88-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ukeafww88-python 
  name: ukeafww88-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ukeafww88-python 
